// Generated by Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSCoder;

SWIFT_CLASS("_TtC16PickerController18PickerControl_Base")
@interface PickerControl_Base : UIControl
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16PickerController25PickerControl_Correlation")
@interface PickerControl_Correlation : PickerControl_Base
- (nonnull instancetype)initWithJsonStr:(NSString * _Nonnull)jsonStr;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

@interface PickerControl_Correlation (SWIFT_EXTENSION(PickerController)) <UIPickerViewDelegate>
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end


@interface PickerControl_Correlation (SWIFT_EXTENSION(PickerController)) <UIPickerViewDataSource>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
@end


SWIFT_CLASS("_TtC16PickerController18PickerControl_Date")
@interface PickerControl_Date : PickerControl_Base
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16PickerController19PickerControl_Group")
@interface PickerControl_Group : PickerControl_Base
- (nonnull instancetype)initWithData:(NSArray<NSArray<NSString *> *> * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface PickerControl_Group (SWIFT_EXTENSION(PickerController)) <UIPickerViewDelegate>
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
@end


@interface PickerControl_Group (SWIFT_EXTENSION(PickerController)) <UIPickerViewDataSource>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
@end

@class NSBundle;

SWIFT_CLASS("_TtC16PickerController21PickerController_Base")
@interface PickerController_Base : UIViewController
@property (nonatomic) CGFloat height;
@property (nonatomic) NSTimeInterval animateDuration;
@property (nonatomic) CGFloat backgroundAlpha;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC16PickerController28PickerController_Correlation")
@interface PickerController_Correlation : PickerController_Base
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title correlationalJsonStr:(NSString * _Nonnull)correlationalJsonStr onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setSelectedWithItems:(NSArray<NSString *> * _Nonnull)items;
- (void)setSelectedWithIndices:(NSArray<NSNumber *> * _Nonnull)indices;
- (void)setDoneAction:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone;
@end


SWIFT_CLASS("_TtC16PickerController21PickerController_Date")
@interface PickerController_Date : PickerController_Base
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title onDone:(void (^ _Nullable)(NSDate * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setDateWithDate:(NSDate * _Nonnull)date;
- (void)setDoneAction:(void (^ _Nullable)(NSDate * _Nonnull))onDone;
@end


SWIFT_CLASS("_TtC16PickerController22PickerController_Group")
@interface PickerController_Group : PickerController_Base
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title groupData:(NSArray<NSArray<NSString *> *> * _Nonnull)groupData onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setSelectedWithItems:(NSArray<NSString *> * _Nonnull)items;
- (void)setSelectedWithIndices:(NSArray<NSNumber *> * _Nonnull)indices;
- (void)setDoneAction:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone;
@end


@interface UIViewController (SWIFT_EXTENSION(PickerController))
- (void)showPicker_ChineseRegionalismWithTitle:(NSString * _Nonnull)title selectedItems:(NSArray<NSString *> * _Nonnull)selectedItems onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel;
@end


@interface UIViewController (SWIFT_EXTENSION(PickerController))
@end


@interface UIViewController (SWIFT_EXTENSION(PickerController))
- (void)showCorrelationPickerWithTitle:(NSString * _Nonnull)title correlationalJsonStr:(NSString * _Nonnull)correlationalJsonStr selectedItems:(NSArray<NSString *> * _Nonnull)selectedItems onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel;
- (void)showCorrelationPickerWithTitle:(NSString * _Nonnull)title correlationalJsonStr:(NSString * _Nonnull)correlationalJsonStr selectedIndices:(NSArray<NSNumber *> * _Nonnull)selectedIndices onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel;
- (void)showCorrelationPickerWithTitle:(NSString * _Nonnull)title correlationalJsonFile:(NSString * _Nonnull)correlationalJsonFile selectedItems:(NSArray<NSString *> * _Nonnull)selectedItems onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel;
- (void)showCorrelationPickerWithTitle:(NSString * _Nonnull)title correlationalJsonFile:(NSString * _Nonnull)correlationalJsonFile selectedIndices:(NSArray<NSNumber *> * _Nonnull)selectedIndices onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel;
- (void)showGroupPickerWithTitle:(NSString * _Nonnull)title groupData:(NSArray<NSArray<NSString *> *> * _Nonnull)groupData selectedItems:(NSArray<NSString *> * _Nonnull)selectedItems onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel;
- (void)showGroupPickerWithTitle:(NSString * _Nonnull)title groupData:(NSArray<NSArray<NSString *> *> * _Nonnull)groupData selectedIndices:(NSArray<NSNumber *> * _Nonnull)selectedIndices onDone:(void (^ _Nullable)(NSArray<NSNumber *> * _Nonnull, NSArray<NSString *> * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel;
- (void)showDatePickerWithTitle:(NSString * _Nonnull)title initialDate:(NSDate * _Nonnull)initialDate onDone:(void (^ _Nullable)(NSDate * _Nonnull))onDone onCancel:(void (^ _Nullable)(void))onCancel;
@end

#pragma clang diagnostic pop
